-- ============================================================
-- MALOOKKYYY BIRTHDAY SITE — V5 FULL SUPABASE SETUP
-- ============================================================
-- Run this ONCE in Supabase > SQL Editor.
-- Starting guest PIN: 2912
-- Owner account is created separately in Authentication > Users.
-- Then run supabase/owner.sql with your owner email.
-- ============================================================

create extension if not exists pgcrypto;

-- -----------------------------
-- SITE SETTINGS / GUEST PIN
-- -----------------------------
create table if not exists public.birthday_settings (
  id integer primary key check (id = 1),
  code_hash text not null,
  updated_at timestamptz not null default now()
);

insert into public.birthday_settings (id, code_hash)
values (1, encode(digest(convert_to('2912','UTF8'),'sha256'),'hex'))
on conflict (id) do nothing;

-- -----------------------------
-- OWNER ACCOUNTS
-- -----------------------------
create table if not exists public.birthday_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

-- -----------------------------
-- GALLERY
-- -----------------------------
create table if not exists public.gallery_categories (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(trim(name)) between 1 and 60),
  sort_order integer not null default 10,
  created_at timestamptz not null default now()
);

create table if not exists public.gallery_media (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.gallery_categories(id) on delete restrict,
  media_type text not null check (media_type in ('image','video')),
  storage_path text not null unique,
  caption text not null default '' check (char_length(caption) <= 180),
  sort_order integer not null default 10,
  created_at timestamptz not null default now()
);

-- Initial slider categories. All Memories is generated automatically in JS.
insert into public.gallery_categories(name,sort_order)
values ('21/6',10),('22/7',20),('Gym',30),('In Cairoo',40)
on conflict (name) do nothing;

-- -----------------------------
-- MEMORIES TIMELINE
-- -----------------------------
create table if not exists public.memories (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) between 1 and 80),
  body text not null check (char_length(trim(body)) between 1 and 300),
  sort_order integer not null default 10,
  created_at timestamptz not null default now()
);

insert into public.memories(title,body,sort_order)
select * from (values
  ('21/6','The beginning of a favorite chapter.',10),
  ('22/7','Another sweet memory to keep.',20),
  ('Gym','Growing stronger together.',30),
  ('In Cairoo','Small moments in our favorite city.',40)
) as v(title,body,sort_order)
where not exists (select 1 from public.memories);

-- -----------------------------
-- NOTES: TO DO + WEDDING SONGS
-- -----------------------------
create table if not exists public.birthday_todos (
  id bigint generated by default as identity primary key,
  item text not null check (char_length(trim(item)) between 2 and 180),
  completed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.wedding_songs (
  id bigint generated by default as identity primary key,
  song text not null check (char_length(trim(song)) between 2 and 180),
  created_at timestamptz not null default now()
);

-- -----------------------------
-- STORAGE BUCKET
-- Public URL keeps GitHub Pages simple; only owner can upload/delete.
-- -----------------------------
insert into storage.buckets (id,name,public,file_size_limit)
values ('gallery-media','gallery-media',true,104857600)
on conflict (id) do update set public=true, file_size_limit=104857600;

-- -----------------------------
-- RLS ON FOR EVERYTHING
-- -----------------------------
alter table public.birthday_settings enable row level security;
alter table public.birthday_admins enable row level security;
alter table public.gallery_categories enable row level security;
alter table public.gallery_media enable row level security;
alter table public.memories enable row level security;
alter table public.birthday_todos enable row level security;
alter table public.wedding_songs enable row level security;

-- No direct public table access. Visitors use code-checked RPC functions.
revoke all on public.birthday_settings from anon, authenticated;
revoke all on public.birthday_admins from anon, authenticated;
revoke all on public.gallery_categories from anon, authenticated;
revoke all on public.gallery_media from anon, authenticated;
revoke all on public.memories from anon, authenticated;
revoke all on public.birthday_todos from anon, authenticated;
revoke all on public.wedding_songs from anon, authenticated;

-- ============================================================
-- PASSWORD CHECK
-- ============================================================
create or replace function public.verify_site_code(p_code text)
returns boolean
language sql
security definer
set search_path = public, extensions
as $$
  select exists (
    select 1 from public.birthday_settings
    where id=1
      and encode(digest(convert_to(coalesce(p_code,''),'UTF8'),'sha256'),'hex') = code_hash
  );
$$;
revoke execute on function public.verify_site_code(text) from public;
grant execute on function public.verify_site_code(text) to anon, authenticated;

-- ============================================================
-- OWNER CHECK
-- ============================================================
create or replace function public.is_birthday_owner()
returns boolean
language sql
security definer
set search_path = public
as $$
  select auth.uid() is not null
     and exists (select 1 from public.birthday_admins where user_id=auth.uid());
$$;
revoke execute on function public.is_birthday_owner() from public;
grant execute on function public.is_birthday_owner() to authenticated;

-- ============================================================
-- OWNER DIRECT TABLE POLICIES
-- Dashboard CRUD uses normal Supabase table calls, but only for owner.
-- ============================================================
drop policy if exists owner_all_categories on public.gallery_categories;
create policy owner_all_categories on public.gallery_categories for all to authenticated
using (public.is_birthday_owner()) with check (public.is_birthday_owner());

drop policy if exists owner_all_media on public.gallery_media;
create policy owner_all_media on public.gallery_media for all to authenticated
using (public.is_birthday_owner()) with check (public.is_birthday_owner());

drop policy if exists owner_all_memories on public.memories;
create policy owner_all_memories on public.memories for all to authenticated
using (public.is_birthday_owner()) with check (public.is_birthday_owner());

drop policy if exists owner_all_todos on public.birthday_todos;
create policy owner_all_todos on public.birthday_todos for all to authenticated
using (public.is_birthday_owner()) with check (public.is_birthday_owner());

drop policy if exists owner_all_songs on public.wedding_songs;
create policy owner_all_songs on public.wedding_songs for all to authenticated
using (public.is_birthday_owner()) with check (public.is_birthday_owner());

-- Needed because earlier REVOKE removed grants; RLS still restricts these to owner.
grant select,insert,update,delete on public.gallery_categories to authenticated;
grant select,insert,update,delete on public.gallery_media to authenticated;
grant select,insert,update,delete on public.memories to authenticated;
grant select,insert,update,delete on public.birthday_todos to authenticated;
grant select,insert,update,delete on public.wedding_songs to authenticated;
grant usage,select on all sequences in schema public to authenticated;

-- ============================================================
-- OWNER STORAGE POLICIES
-- ============================================================
drop policy if exists birthday_owner_storage_insert on storage.objects;
create policy birthday_owner_storage_insert on storage.objects for insert to authenticated
with check (bucket_id='gallery-media' and public.is_birthday_owner());

drop policy if exists birthday_owner_storage_update on storage.objects;
create policy birthday_owner_storage_update on storage.objects for update to authenticated
using (bucket_id='gallery-media' and public.is_birthday_owner())
with check (bucket_id='gallery-media' and public.is_birthday_owner());

drop policy if exists birthday_owner_storage_delete on storage.objects;
create policy birthday_owner_storage_delete on storage.objects for delete to authenticated
using (bucket_id='gallery-media' and public.is_birthday_owner());

-- ============================================================
-- PUBLIC GALLERY RPCs — guest PIN required
-- ============================================================
create or replace function public.get_gallery_categories(p_code text)
returns table(id bigint,name text,sort_order integer)
language plpgsql security definer set search_path=public,extensions
as $$
begin
  if not public.verify_site_code(p_code) then raise exception 'Wrong birthday password'; end if;
  return query select c.id,c.name,c.sort_order from public.gallery_categories c order by c.sort_order,c.id;
end; $$;
revoke execute on function public.get_gallery_categories(text) from public;
grant execute on function public.get_gallery_categories(text) to anon, authenticated;

create or replace function public.get_gallery_media(p_code text)
returns table(id bigint,category_id bigint,category_name text,media_type text,storage_path text,caption text,sort_order integer)
language plpgsql security definer set search_path=public,extensions
as $$
begin
  if not public.verify_site_code(p_code) then raise exception 'Wrong birthday password'; end if;
  return query
    select m.id,m.category_id,c.name,m.media_type,m.storage_path,m.caption,m.sort_order
    from public.gallery_media m join public.gallery_categories c on c.id=m.category_id
    order by m.sort_order,m.id;
end; $$;
revoke execute on function public.get_gallery_media(text) from public;
grant execute on function public.get_gallery_media(text) to anon, authenticated;

-- ============================================================
-- PUBLIC MEMORIES RPC — guest PIN required
-- ============================================================
create or replace function public.get_memories(p_code text)
returns table(id bigint,title text,body text,sort_order integer)
language plpgsql security definer set search_path=public,extensions
as $$
begin
  if not public.verify_site_code(p_code) then raise exception 'Wrong birthday password'; end if;
  return query select m.id,m.title,m.body,m.sort_order from public.memories m order by m.sort_order,m.id;
end; $$;
revoke execute on function public.get_memories(text) from public;
grant execute on function public.get_memories(text) to anon, authenticated;

-- ============================================================
-- PUBLIC TO DO RPCs — guest PIN required
-- ============================================================
create or replace function public.get_todos(p_code text)
returns setof public.birthday_todos
language plpgsql security definer set search_path=public,extensions
as $$
begin
  if not public.verify_site_code(p_code) then raise exception 'Wrong birthday password'; end if;
  return query select * from public.birthday_todos order by completed asc,created_at desc;
end; $$;
revoke execute on function public.get_todos(text) from public;
grant execute on function public.get_todos(text) to anon, authenticated;

create or replace function public.add_todo(p_item text,p_code text)
returns public.birthday_todos
language plpgsql security definer set search_path=public,extensions
as $$
declare r public.birthday_todos;
begin
  if not public.verify_site_code(p_code) then raise exception 'Wrong birthday password'; end if;
  if char_length(trim(coalesce(p_item,'')))<2 then raise exception 'Write a to-do first'; end if;
  insert into public.birthday_todos(item) values(left(trim(p_item),180)) returning * into r;
  return r;
end; $$;
revoke execute on function public.add_todo(text,text) from public;
grant execute on function public.add_todo(text,text) to anon, authenticated;

create or replace function public.set_todo_completed(p_todo_id bigint,p_completed boolean,p_code text)
returns void
language plpgsql security definer set search_path=public,extensions
as $$
begin
  if not public.verify_site_code(p_code) then raise exception 'Wrong birthday password'; end if;
  update public.birthday_todos set completed=p_completed where id=p_todo_id;
end; $$;
revoke execute on function public.set_todo_completed(bigint,boolean,text) from public;
grant execute on function public.set_todo_completed(bigint,boolean,text) to anon, authenticated;

-- ============================================================
-- PUBLIC WEDDING SONG RPCs — song name only
-- ============================================================
create or replace function public.get_wedding_songs(p_code text)
returns setof public.wedding_songs
language plpgsql security definer set search_path=public,extensions
as $$
begin
  if not public.verify_site_code(p_code) then raise exception 'Wrong birthday password'; end if;
  return query select * from public.wedding_songs order by created_at desc;
end; $$;
revoke execute on function public.get_wedding_songs(text) from public;
grant execute on function public.get_wedding_songs(text) to anon, authenticated;

create or replace function public.add_wedding_song(p_song text,p_code text)
returns public.wedding_songs
language plpgsql security definer set search_path=public,extensions
as $$
declare r public.wedding_songs;
begin
  if not public.verify_site_code(p_code) then raise exception 'Wrong birthday password'; end if;
  if char_length(trim(coalesce(p_song,'')))<2 then raise exception 'Type a song name first'; end if;
  insert into public.wedding_songs(song) values(left(trim(p_song),180)) returning * into r;
  return r;
end; $$;
revoke execute on function public.add_wedding_song(text,text) from public;
grant execute on function public.add_wedding_song(text,text) to anon, authenticated;

-- ============================================================
-- OWNER FUNCTIONS
-- ============================================================
create or replace function public.owner_set_site_code(p_code text)
returns void
language plpgsql security definer set search_path=public,extensions
as $$
begin
  if not public.is_birthday_owner() then raise exception 'Owner only'; end if;
  if p_code !~ '^[0-9]{4}$' then raise exception 'PIN must be exactly 4 digits'; end if;
  update public.birthday_settings
  set code_hash=encode(digest(convert_to(p_code,'UTF8'),'sha256'),'hex'), updated_at=now()
  where id=1;
end; $$;
revoke execute on function public.owner_set_site_code(text) from public;
grant execute on function public.owner_set_site_code(text) to authenticated;

create or replace function public.delete_gallery_media_admin(p_media_id bigint)
returns text
language plpgsql security definer set search_path=public
as $$
declare p text;
begin
  if not public.is_birthday_owner() then raise exception 'Owner only'; end if;
  delete from public.gallery_media where id=p_media_id returning storage_path into p;
  return p;
end; $$;
revoke execute on function public.delete_gallery_media_admin(bigint) from public;
grant execute on function public.delete_gallery_media_admin(bigint) to authenticated;
