-- ============================================================
-- MALOOKKYYY BIRTHDAY SITE — SUPABASE SETUP
-- ============================================================
-- Run this once in Supabase > SQL Editor.
-- Before running the final admin functions, replace:
--   REPLACE_WITH_YOUR_ADMIN_USER_UUID
-- with the UUID of the owner account you create in Authentication > Users.

create extension if not exists pgcrypto;

create table if not exists public.birthday_settings (
  id int primary key default 1 check (id = 1),
  code_hash text not null
);

-- SHA-256 hash of the private four-digit code. The plain code is not stored in this repo.
insert into public.birthday_settings (id, code_hash)
values (1, '5c9a7f508de2f1ec87076e88a888f9af847c69d68565ab6a6983fc8b497fa1f8')
on conflict (id) do update set code_hash = excluded.code_hash;

create table if not exists public.birthday_todos (
  id bigint generated by default as identity primary key,
  item text not null check (char_length(trim(item)) between 2 and 180),
  completed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.wedding_songs (
  id bigint generated by default as identity primary key,
  song text not null check (char_length(trim(song)) between 2 and 180),
  added_by text not null check (char_length(trim(added_by)) between 2 and 60),
  created_at timestamptz not null default now()
);

alter table public.birthday_settings enable row level security;
alter table public.birthday_todos enable row level security;
alter table public.wedding_songs enable row level security;

revoke all on public.birthday_settings from anon, authenticated;
revoke all on public.birthday_todos from anon, authenticated;
revoke all on public.wedding_songs from anon, authenticated;

create or replace function public.verify_site_code(p_code text)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.birthday_settings
    where id = 1 and encode(digest(p_code, 'sha256'), 'hex') = code_hash
  );
$$;
grant execute on function public.verify_site_code(text) to anon, authenticated;

create or replace function public.get_todos(p_code text)
returns setof public.birthday_todos
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.verify_site_code(p_code) then raise exception 'Wrong birthday password'; end if;
  return query select * from public.birthday_todos order by completed asc, created_at desc;
end;
$$;
grant execute on function public.get_todos(text) to anon, authenticated;

create or replace function public.add_todo(p_item text, p_code text)
returns public.birthday_todos
language plpgsql
security definer
set search_path = public
as $$
declare new_row public.birthday_todos;
begin
  if not public.verify_site_code(p_code) then raise exception 'Wrong birthday password'; end if;
  insert into public.birthday_todos(item) values (trim(p_item)) returning * into new_row;
  return new_row;
end;
$$;
grant execute on function public.add_todo(text,text) to anon, authenticated;

create or replace function public.set_todo_completed(p_todo_id bigint, p_completed boolean, p_code text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.verify_site_code(p_code) then raise exception 'Wrong birthday password'; end if;
  update public.birthday_todos set completed = p_completed where id = p_todo_id;
end;
$$;
grant execute on function public.set_todo_completed(bigint,boolean,text) to anon, authenticated;

create or replace function public.get_wedding_songs(p_code text)
returns setof public.wedding_songs
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.verify_site_code(p_code) then raise exception 'Wrong birthday password'; end if;
  return query select * from public.wedding_songs order by created_at desc;
end;
$$;
grant execute on function public.get_wedding_songs(text) to anon, authenticated;

create or replace function public.add_wedding_song(p_song text, p_added_by text, p_code text)
returns public.wedding_songs
language plpgsql
security definer
set search_path = public
as $$
declare new_row public.wedding_songs;
begin
  if not public.verify_site_code(p_code) then raise exception 'Wrong birthday password'; end if;
  insert into public.wedding_songs(song, added_by)
  values (trim(p_song), trim(p_added_by))
  returning * into new_row;
  return new_row;
end;
$$;
grant execute on function public.add_wedding_song(text,text,text) to anon, authenticated;

-- Owner-only delete controls.
create or replace function public.delete_todo_admin(p_todo_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null or auth.uid() <> 'REPLACE_WITH_YOUR_ADMIN_USER_UUID'::uuid then raise exception 'Owner only'; end if;
  delete from public.birthday_todos where id = p_todo_id;
end;
$$;
grant execute on function public.delete_todo_admin(bigint) to authenticated;

create or replace function public.delete_song_admin(p_song_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null or auth.uid() <> 'REPLACE_WITH_YOUR_ADMIN_USER_UUID'::uuid then raise exception 'Owner only'; end if;
  delete from public.wedding_songs where id = p_song_id;
end;
$$;
grant execute on function public.delete_song_admin(bigint) to authenticated;
