-- MALOOKKYYY BIRTHDAY NOTES SETUP
-- Run this once in Supabase > SQL Editor.
-- IMPORTANT: before running, replace REPLACE_WITH_YOUR_ADMIN_USER_UUID below.
-- Create your admin user first in Authentication > Users, then copy its UUID.

create extension if not exists pgcrypto;

create table if not exists public.birthday_settings (
  id int primary key default 1 check (id = 1),
  code_hash text not null
);

insert into public.birthday_settings (id, code_hash)
values (1, crypt('2912', gen_salt('bf')))
on conflict (id) do update set code_hash = excluded.code_hash;

create table if not exists public.birthday_notes (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 60),
  message text not null check (char_length(message) between 2 and 1200),
  created_at timestamptz not null default now()
);

alter table public.birthday_settings enable row level security;
alter table public.birthday_notes enable row level security;

-- No direct table access from the browser. Everything goes through controlled RPCs.
revoke all on public.birthday_settings from anon, authenticated;
revoke all on public.birthday_notes from anon, authenticated;

create or replace function public.verify_site_code(p_code text)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.birthday_settings
    where id = 1 and crypt(p_code, code_hash) = code_hash
  );
$$;

grant execute on function public.verify_site_code(text) to anon, authenticated;

create or replace function public.get_notes(p_code text)
returns setof public.birthday_notes
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.verify_site_code(p_code) then
    raise exception 'Wrong birthday password';
  end if;
  return query select * from public.birthday_notes order by created_at desc;
end;
$$;

grant execute on function public.get_notes(text) to anon, authenticated;

create or replace function public.add_note(p_name text, p_message text, p_code text)
returns public.birthday_notes
language plpgsql
security definer
set search_path = public
as $$
declare
  new_note public.birthday_notes;
begin
  if not public.verify_site_code(p_code) then
    raise exception 'Wrong birthday password';
  end if;
  insert into public.birthday_notes(name, message)
  values (trim(p_name), trim(p_message))
  returning * into new_note;
  return new_note;
end;
$$;

grant execute on function public.add_note(text,text,text) to anon, authenticated;

create or replace function public.delete_note_admin(p_note_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null or auth.uid() <> 'REPLACE_WITH_YOUR_ADMIN_USER_UUID'::uuid then
    raise exception 'Admin only';
  end if;
  delete from public.birthday_notes where id = p_note_id;
end;
$$;

grant execute on function public.delete_note_admin(bigint) to authenticated;
